[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "pyvoltic"
authors = [
    {name = "Leo Loman", email = "leo.loman@outlook.com"},
]
description = "A framework for the Edge Based Compartmental Model (Volz Miller) equations"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["ebcm", "edge based compartmental model"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3"
]
dependencies = [    
    "numpy",
    "scipy",
    "networkx",
    "matplotlib"
]

[project.optional-dependencies]
abc = ["pyabc"]

[project.scripts]
exclude = '''
/(
  | \.git          # root of the project
  | build
  | dist
  | doc
)/
'''
