name: run_mode_test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install numpy scipy matplotlib pytest
    - name: test with pytest
      run: |
        python3 -m pytest -v tests/test_pyvoltic.py
