name: run_mode_test
on:
    pull_request:
      branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install scipy
        pip install pytest
        pip install matplotlib
        pip install -e .
    - name: test with pytest
      run: |
        python3 -m pytest -v tests/test_pyvoltic.py
    - name: Run pre-commit yaml
      run:  |
        pre-commit run --all-files
